### Arithmetic Functions on NumPy Arrays

In [1]:
import pandas as pd
import numpy as np
import faker

In [2]:
fake = faker.Faker()

In [3]:
def create_fake_data():
    return {
        "Name" : fake.name(),
        "Age" : np.random.randint(low = 18, high = 60, size = 1)
    }

In [4]:
create_fake_data()

{'Name': 'Gregory Aguilar', 'Age': array([25])}

In [5]:
data = pd.DataFrame(columns = ['Name', 'Age'])
for _ in range(10):
    new_data = pd.DataFrame(create_fake_data())
    data = pd.concat([data, new_data], ignore_index = True)
data.head()

Name Age
0       Tracey Ward  27
1   Michael Johnson  42
2         Paul Webb  32
3  Richard Guerrero  32
4    Alicia Johnson  33

In [6]:
data

Name Age
0       Tracey Ward  27
1   Michael Johnson  42
2         Paul Webb  32
3  Richard Guerrero  32
4    Alicia Johnson  33
5    Nathaniel Hill  22
6        Jason Barr  41
7       Lisa Jordan  24
8       Mary Garcia  18
9     Joseph Howard  56

In [7]:
print(f"Maximum age is {np.max(data['Age'])}")
print(f"Minimum age is {np.min(data['Age'])}")
print(f"Index where the maximum value of age is present is {np.argmax(data['Age'])}")
print(f"Index where the minimum value of age is present is {np.argmin(data['Age'])}")
print(f"Square roots of {[4, 9, 16, 25, 36]} are {np.sqrt([4, 9, 16, 25, 36])}")
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
print(f"Sine of angles are {np.sin(angles).astype(int)}")
print(f"Cosine of angles are {np.cos(angles).astype(int)}")
print(f"The cumulative sum of ages are \n{np.cumsum(data['Age'])}")

Maximum age is 56
Minimum age is 18
Index where the maximum value of age is present is 9
Index where the minimum value of age is present is 8
Square roots of [4, 9, 16, 25, 36] are [2. 3. 4. 5. 6.]
Sine of angles are [ 0  1  0 -1]
Cosine of angles are [ 1  0 -1  0]
The cumulative sum of ages are 
0     27
1     69
2    101
3    133
4    166
5    188
6    229
7    253
8    271
9    327
Name: Age, dtype: object


In [8]:
two_dimensional_array = [[1,2,10,9], [5,6,-1,4]]
print(two_dimensional_array)
print(np.max(two_dimensional_array, axis = 1)) #Prints the maximum element from each row
print(np.max(two_dimensional_array, axis = 0)) #Prints the maximum element from each column
print(np.argmax(two_dimensional_array, axis = 1)) #Prints the index of the maximum element from each row
print(np.argmax(two_dimensional_array, axis = 0)) #Prints the index of the maximum element from each column

[[1, 2, 10, 9], [5, 6, -1, 4]]
[10  6]
[ 5  6 10  9]
[2 1]
[1 1 0 0]


In [9]:
np.max(data['Name'])

'Tracey Ward'

In [10]:
arr = np.array([2 for _ in range(10)])
np.cumproduct(arr)
np.cumprod(arr)

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])