### Arithmetic Functions on NumPy Arrays

In [1]:
import pandas as pd
import numpy as np
import faker

In [2]:
fake = faker.Faker()

In [3]:
def create_fake_data():
    return {
        "Name" : fake.name(),
        "Age" : np.random.randint(low = 18, high = 60, size = 1)
    }

In [4]:
create_fake_data()

{'Name': 'Miranda Dillon', 'Age': array([59])}

In [5]:
data = pd.DataFrame(columns = ['Name', 'Age'])
for _ in range(10):
    new_data = pd.DataFrame(create_fake_data())
    data = pd.concat([data, new_data], ignore_index = True)
data.head()

Name Age
0         Holly Smith  35
1   Elizabeth Mercado  38
2         Jordan King  46
3    Daniel Jefferson  23
4  Samantha Hernandez  34

In [6]:
data

Name Age
0         Holly Smith  35
1   Elizabeth Mercado  38
2         Jordan King  46
3    Daniel Jefferson  23
4  Samantha Hernandez  34
5          Mark Jones  41
6       Ann Hernandez  44
7      Patricia Smith  25
8     Jean Cunningham  43
9       Julia Simmons  41

In [7]:
print(f"Maximum age is {np.max(data['Age'])}")
print(f"Minimum age is {np.min(data['Age'])}")
print(f"Index where the maximum value of age is present is {np.argmax(data['Age'])}")
print(f"Index where the minimum value of age is present is {np.argmin(data['Age'])}")
print(f"Square roots of {[4, 9, 16, 25, 36]} are {np.sqrt([4, 9, 16, 25, 36])}")
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
print(f"Sine of angles are {np.sin(angles).astype(int)}")
print(f"Cosine of angles are {np.cos(angles).astype(int)}")
print(f"The cumulative sum of ages are \n{np.cumsum(data['Age'])}")

Maximum age is 46
Minimum age is 23
Index where the maximum value of age is present is 2
Index where the minimum value of age is present is 3
Square roots of [4, 9, 16, 25, 36] are [2. 3. 4. 5. 6.]
Sine of angles are [ 0  1  0 -1]
Cosine of angles are [ 1  0 -1  0]
The cumulative sum of ages are 
0     35
1     73
2    119
3    142
4    176
5    217
6    261
7    286
8    329
9    370
Name: Age, dtype: object


In [11]:
two_dimensional_array = [[1,2,10,9], [5,6,-1,4]]
print(two_dimensional_array)
print(np.max(two_dimensional_array, axis = 1)) #Prints the maximum element from each row
print(np.max(two_dimensional_array, axis = 0)) #Prints the maximum element from each column
print(np.argmax(two_dimensional_array, axis = 1)) #Prints the index of the maximum element from each row
print(np.argmax(two_dimensional_array, axis = 0)) #Prints the index of the maximum element from each column

[[1, 2, 10, 9], [5, 6, -1, 4]]
[10  6]
[ 5  6 10  9]
[2 1]
[1 1 0 0]


In [12]:
np.max(data['Name'])

'Samantha Hernandez'

In [22]:
arr = np.array([2 for _ in range(10)])
np.cumproduct(arr)
np.cumprod(arr)

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [23]:
import pandas as pd
import numpy as np

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Salary': [50000, 60000, 55000, 65000, 70000, 72000]
}

df = pd.DataFrame(data)

In [31]:
grouped = df.groupby(by = ['Department'])
grouped.get_group(name = ['HR'])

TypeError: unhashable type: 'list'