### Broadcasting in NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
first = np.array(object = [1,2,3,4])
second = np.array(object = [1,2,3])

In [3]:
print(first + second)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
"""The above error is related to Broadcasting and it is due to the difference in the shapes 
of the arrays.
When performing operations on two arrays, NumPy compares their shapes element-wise, starting from the last dimension 
and working backwards. 

It applies these broadcasting rules to make the arrays compatible for element-wise operations:
Rule 1: If the dimensions of the two arrays are not the same, NumPy will "stretch" (broadcast) the smaller array 
along the larger array’s dimension.

If one of the arrays has a shape of size 1 in a particular dimension, it will be repeated along that dimension 
to match the other array.
Rule 2: If the arrays still don’t have the same shape after applying Rule 1, NumPy will raise an error, 
indicating that they are not compatible.
"""
np.array([1,2,3]) + np.array([1,2,3], ndmin = 3)

array([[[2, 4, 6]]])

### Indexing and Slicing in NumPy Arrays

In [11]:
np.array([
        [[1,2], [1,2]], #Block 0
        [[1,2],[1,2]]   #Block 1
         ])

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [18]:
arr = [0,1,2,3,4,5]
for index in range(6):
    print(arr[index], end = " ")
print("\n")
for index in range(-1, -7, -1):
    print(arr[index], end = " ")

0 1 2 3 4 5 

5 4 3 2 1 0 

In [30]:
two_dimensional_array = np.array(object = [[9,8,7], [4,5,6]])
print(two_dimensional_array[0,1])
print(two_dimensional_array[0][1]) # This and the above syntax, both are identical in working
print(two_dimensional_array[1,1])

8
8
5


In [35]:
for row_index in range(two_dimensional_array.shape[0]):
    for column_index in range(two_dimensional_array.shape[1]):
        print(two_dimensional_array[row_index, column_index], end = " ")

9 8 7 4 5 6 

In [47]:
three_dimensional_array = [
    [
        [1,2], #Block 0 Row 0
        [1,2]  #Block 0 Row 1
    ], 

    [
        [1,2], #Block 1 Row 0
        [1,2]  #Block 1 Row 1
    ]
]
three_dimensional_array = np.array(three_dimensional_array)

In [54]:
print(three_dimensional_array[0,1,1]) # Access the element from the 0th block, 1st row, 1st column
print(three_dimensional_array[1,0,0]) # Access the element from the 1st block, 0th row, 0th column

2
1


In [56]:
one_dimensional_array = [x for x in range(10)]
one_dimensional_array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
one_dimensional_array[0:9]
one_dimensional_array[2:5]
one_dimensional_array[0:10:2]
one_dimensional_array[:10]
one_dimensional_array[2:]
one_dimensional_array[:]
one_dimensional_array[::3]

[0, 3, 6, 9]

In [65]:
two_dimensional_array

array([[9, 8, 7],
       [4, 5, 6]])

In [73]:
two_dimensional_array[0:2]
two_dimensional_array[0:1, :]
two_dimensional_array[0:1, 1:]
two_dimensional_array[:, 2:]
two_dimensional_array[:, 0:]
two_dimensional_array[0:, :2]

array([[9, 8],
       [4, 5]])