### Iterating through Arrays in NumPy

In [2]:
import pandas as pd
import numpy as np

In [6]:
one_dimensional_array = np.array([x for x in range(10)])
one_dimensional_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
for item in one_dimensional_array:
    print(item, end = " ")

print("")

for index in range(one_dimensional_array.shape[0]):
    print(one_dimensional_array[index], end = " ")

0 1 2 3 4 5 6 7 8 9 
0 1 2 3 4 5 6 7 8 9 

In [13]:
two_dimensional_array = np.array([
    [1,2], 
    [3,4]
])
two_dimensional_array

array([[1, 2],
       [3, 4]])

In [18]:
for item in two_dimensional_array:
    print(item)

print("")

for outer_index in range(two_dimensional_array.shape[0]):
    for inner_index in range(two_dimensional_array.shape[1]):
        print(two_dimensional_array[outer_index, inner_index], end = " ")
    
print("\n")

for row in two_dimensional_array:
    for item in row:
        print(item, end = " ")

[1 2]
[3 4]

1 2 3 4 

1 2 3 4 

In [23]:
three_dimensional_array = np.array([
    [
        [1,2,3], 
        [4,5,6]
    ], 
    [
        [1,2,3], 
        [4,5,6]
    ]
])
three_dimensional_array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [31]:
for block in three_dimensional_array:
    for row in block:
        for value in row:
            print(value, end = " ")
    print("")

print("")
    
for block_index in range(three_dimensional_array.shape[0]):
    for row_index in range(three_dimensional_array.shape[1]):
        for column_index in range(three_dimensional_array.shape[2]):
            print(three_dimensional_array[block_index, row_index, column_index], end = " ")
        print("")

1 2 3 4 5 6 
1 2 3 4 5 6 

1 2 3 
4 5 6 
1 2 3 
4 5 6 


In [33]:
"""Instead of using multiple for loops for multi-dimensional data, we can use the inbuilt nditer function 
to access all the values present in the array"""
for item in np.nditer(three_dimensional_array):
    print(item, end = " ")

1 2 3 4 5 6 1 2 3 4 5 6 

In [38]:
for index, value in np.ndenumerate(three_dimensional_array):
    print(index, value)

[(0, 0, 0), 1]
[(0, 0, 1), 2]
[(0, 0, 2), 3]
[(0, 1, 0), 4]
[(0, 1, 1), 5]
[(0, 1, 2), 6]
[(1, 0, 0), 1]
[(1, 0, 1), 2]
[(1, 0, 2), 3]
[(1, 1, 0), 4]
[(1, 1, 1), 5]
[(1, 1, 2), 6]


### Copy and View in NumPy

In [39]:
import pandas as pd
import numpy as np

In [40]:
arr = np.array(object = [1,2,3,4,5])
copy_arr = arr.copy()

In [42]:
print(f"Original Array {arr}")
print(f"Copied Array {copy_arr}")

Original Array [1 2 3 4 5]
Copied Array [1 2 3 4 5]


In [44]:
data = np.array([9,8,7,6,5])
view_data = data.view()

print(f"Original Array {data}")
print(f"View of Array {view_data}")

Original Array [9 8 7 6 5]
View of Array [9 8 7 6 5]


In [45]:
"""
1. A copy of a NumPy array creates a completely new array that is independent of the original array. 
Changes made to the copy do not affect the original array, and vice versa.

2. A view (also called a shallow copy) is a new array object that refers to the same data as the original array. 
Changes made to the view will affect the original array, and vice versa, because they share the same underlying data.
"""

copy_arr[0] = 100
print(f"Original Array {arr}")
print(f"Copied Array {copy_arr}")

view_data[0] = 100
print(f"Original Array {data}")
print(f"View of Array {view_data}")

Original Array [1 2 3 4 5]
Copied Array [100   2   3   4   5]
Original Array [100   8   7   6   5]
View of Array [100   8   7   6   5]
