### Joining and Splitting Arrays in NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
"""Joining means putting the contents of 2 or more arrays in a single array"""
first = np.array([1,2,3,4])
second = np.array([1,2,3,4])

final_array = np.concatenate([first, second])
final_array

array([1, 2, 3, 4, 1, 2, 3, 4])

In [3]:
"""Joining Two Dimensional Arrays"""
first = np.array([
    [1,2,3,4], 
    [5,6,7,8]
])

second = np.array([
    [1,2,3,4], 
    [5,6,7,8]
])

row_join = np.concatenate([first, second], axis = 0)
column_join = np.concatenate([first, second], axis = 1)
"""axis = 0, join row wise
   axis = 1 join column wise"""

row_join, column_join

(array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8]]))

In [4]:
first = np.array([
    [1,2,3,4], 
    [5,6,7,8]
])

second = np.array([
    [1,2,3,4], 
    [5,6,7,8]
])

print(np.stack([first, second], axis = 0)) #Stack arrays vertically
print("")
print(np.stack([first, second], axis = 1)) #Stack arrays horizontally
print("")
print(np.stack([first, second], axis = 2)) #Stack arrays element-wise, creating pairs of elements from each array.

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]

[[[1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [5 6 7 8]]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]]

 [[5 5]
  [6 6]
  [7 7]
  [8 8]]]


In [5]:
a = np.array([[1, 2], 
              [3, 4]])

b = np.array([[5, 6], 
              [7, 8]])
stacked_axis_1 = np.stack((a, b), axis=1)
"""
[[[1 2]  [5 6]]   # Row 0: a's first row is paired with b's first row
 [[3 4]  [7 8]]]   # Row 1: a's second row is paired with b's second row
"""
print(stacked_axis_1)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [6]:
np.vstack([first, second]) # Vertical Stacking
np.hstack([first, second]) # Horizontal Stacking
np.dstack([first, second]) # Element-Wise Stacking

array([[[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]],

       [[5, 5],
        [6, 6],
        [7, 7],
        [8, 8]]])

### Splitting Arrays in NumPy

In [7]:
import pandas as pd
import numpy as np

In [13]:
first = np.array(object = [x for x in range(6)])
first

array([0, 1, 2, 3, 4, 5])

In [14]:
np.split(ary = first, indices_or_sections = 3, axis = 0)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [15]:
type(np.split(ary = first, indices_or_sections = 3, axis = 0))

list

In [16]:
np.split(ary = first, indices_or_sections = 3, axis = 0)[0]

array([0, 1])

In [17]:
np.split(ary = first, indices_or_sections = 3, axis = 0)[1]

array([2, 3])

In [18]:
np.split(ary = first, indices_or_sections = 3, axis = 0)[2]

array([4, 5])

In [20]:
np.split(ary = first, indices_or_sections = 3, axis = 0)[0][1]

1

In [28]:
two_dimensional_array = np.array([
    [x for x in range(6)], 
    [x for x in range(6,12)], 
    [x for x in range(12, 18)], 
])
two_dimensional_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [29]:
np.split(ary = two_dimensional_array, indices_or_sections = 3, axis = 0) #Splitting along the rows

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [30]:
np.split(ary = two_dimensional_array, indices_or_sections = 3, axis = 1) #Splitting along the columns

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]