### Data Types in NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array(object = [1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
print(f"Data Type of the variable is {arr.dtype}")

Data Type of the variable is int32


In [4]:
arr = np.array(object = [1.2,2.4,3.5,4.6,5.7])
print(f"Data Type of the variable is {arr.dtype}")

Data Type of the variable is float64


In [5]:
arr = np.array(object = ["s", "a", "b", "c"])
print(f"Data Type of the variable is {arr.dtype}")

Data Type of the variable is <U1


In [6]:
arr = np.array(object = ["s", "a", "b", "c", 1,2,3])
print(f"Data Type of the variable is {arr.dtype}")

Data Type of the variable is <U11


In [7]:
"""Converting a variable to another data type"""
x = np.array([1,2,3,4],)
print(x.dtype)

x = np.array([1,2,3,4],  dtype = np.int8)
print(x.dtype)

x = np.array([1,2,3,4],  dtype = np.float32)
print(x, x.dtype)

x = np.array([1,2,3,4],  dtype = np.str_)
print(x, x.dtype)

int32
int8
[1. 2. 3. 4.] float32
['1' '2' '3' '4'] <U1


In [8]:
int_array = np.array(object = [0,1,2,3,4])
print(int_array, int_array.dtype)

"""Instead of specifying the dtype parameter, NumPy can be used as a function to change the 
data-type of a variable."""

float_array = np.float32(int_array)
print(float_array, float_array.dtype)

bool_array = np.bool_(int_array)
print(bool_array, bool_array.dtype)

[0 1 2 3 4] int32
[0. 1. 2. 3. 4.] float32
[False  True  True  True  True] bool


In [9]:
"""Using astype to convert the data types of variables"""
integers = np.array(object = [1,2,3,4,5])
floats = integers.astype('float')
print(integers)
print(floats)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


### Arithmetic Operations on Array

In [10]:
arr = np.array([1,2,3,4])
print(arr + 3)
print(arr - 3)
print(arr * 3)
print(arr / 3)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]


In [11]:
"""Arithmetic Operations on One Dimensional Arrays"""
first = np.array([1,2,3,4])
second = np.array([1,2,3,4])

print(f"Addition \n{np.add(first, second)}\n")
print(f"Subtraction \n{np.subtract(first, second)}\n")
print(f"Multiplication \n{np.multiply(first, second)}\n")
print(f"Division \n{np.divide(first, second)}\n")
print(f"Modulus \n{np.mod(first, second)}\n")
print(f"Division and Modulus \n{np.divmod(first, second)}\n")
print(f"Reciprocal \n{(np.reciprocal(first, dtype = float))}\n")
print(f"Power \n{np.power(first, 2)}")

Addition 
[2 4 6 8]

Subtraction 
[0 0 0 0]

Multiplication 
[ 1  4  9 16]

Division 
[1. 1. 1. 1.]

Modulus 
[0 0 0 0]

Division and Modulus 
(array([1, 1, 1, 1]), array([0, 0, 0, 0]))

Reciprocal 
[1.         0.5        0.33333333 0.25      ]

Power 
[ 1  4  9 16]


In [12]:
"""Arithmetic Operations on Two Dimensional Arrays"""
first_arr = [[1,2,3,4], [5,6,7,8]]
second_arr = [[1,2,3,4], [5,6,7,8]]

print(f"Addition \n {np.add(first_arr, second_arr)}\n") 
print(f"Subtraction \n {np.subtract(first_arr, second_arr)}\n") 
print(f"Multiplication \n {np.multiply(first_arr, second_arr)}\n") 
print(f"Division \n {np.divide(first_arr, second_arr)}\n") 
print(f"Modulus \n {np.mod(first_arr, second_arr)}\n") 
print(f"Division and Modulus \n{np.divmod(first_arr, second_arr)}\n") 
print(f"Reciprocal \n{(np.reciprocal(first_arr, dtype = float))}\n") 
print(f"Power \n{np.power(first_arr, 2)}")

Addition 
 [[ 2  4  6  8]
 [10 12 14 16]]

Subtraction 
 [[0 0 0 0]
 [0 0 0 0]]

Multiplication 
 [[ 1  4  9 16]
 [25 36 49 64]]

Division 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Modulus 
 [[0 0 0 0]
 [0 0 0 0]]

Division and Modulus 
(array([[1, 1, 1, 1],
       [1, 1, 1, 1]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0]]))

Reciprocal 
[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]]

Power 
[[ 1  4  9 16]
 [25 36 49 64]]
