### Creating Arrays in NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr, type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
lst = []
for _ in range(4):
    lst.append(int(input("Enter a number: ")))

print(lst, type(lst))
print(np.array(lst))

Enter a number: 1
Enter a number: 2
Enter a number: 3
Enter a number: 4
[1, 2, 3, 4] <class 'list'>
[1 2 3 4]


In [4]:
"""Use ndim to check the dimensions of the NumPy Array"""
print(arr.ndim)

1


In [5]:
two_dimensional_array = np.array([[1,2,3,4], [1,2,3,4]])
print(two_dimensional_array)
print(two_dimensional_array.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [6]:
three_dimensional_array = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
print(three_dimensional_array)
print(three_dimensional_array.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [7]:
"""Specifying the dimensions of the NumPy Array"""
np.array([1,2,3,4,5,6,7,8,9,10], ndmin = 10)

array([[[[[[[[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]]]]]]]])

### Special NumPy Arrays

In [8]:
zeroes = np.zeros(shape = (2,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
"""Use zeroes_like to obtain an array with a shape similar 
to an existing array."""
np.zeros_like(a = three_dimensional_array)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [10]:
"""Array filled with 1's"""
ones = np.ones(shape = (2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones_like(a = three_dimensional_array)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [12]:
"""Empty Array"""
np.empty(shape = (4))

array([1.40733086e-311, 7.56601164e-307, 4.34777768e-321, 3.79442416e-321])

In [13]:
np.empty_like(prototype = three_dimensional_array)

array([[[4128860, 6029375, 3801155, 5570652],
        [6619251, 7536754, 7340124, 6357106],
        [7798890, 4259932, 7340144, 6357060]]])

In [14]:
"""Range Array"""
np.arange(start = 10, stop = 15)
np.arange(start = 10, stop = 20, step = 2)
np.arange(stop = 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
"""Creating identity Matrix"""
np.identity(n  = 4)
np.identity(n = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(N = 4)
np.eye(N = 4, M = 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [17]:
"""Creating Arrays having evenly spaced numbers over a specified interval."""
np.linspace(start = 1, stop = 10, num = 20) # Default value of num is 50, which specifies the number of equally spaced intervals
np.linspace(start = 0, stop = 20, num = 5)

array([ 0.,  5., 10., 15., 20.])

In [18]:
"""Arrays having Random Numbers"""
print(np.random.rand()) # Returns a number between 0 and 1
print("")
print(np.random.randn()) # Return a sample (or samples) from the "standard normal" distribution. May include megative values 
print(np.random.randn(5)) # as well
print("")
print(np.random.ranf()) # Used for Random Sampling. Interval is 0 to 1 where 0 is inclusive and 1 is exclusive.
print(np.random.ranf(10))
print("")
print(np.random.randint(low = 0, high = 10, size = 4)) # Returns Random numbers from the specified range
print(np.random.randint(low = 1, high = 1000, size = 10))

0.9900447547247256

-0.45843933718783964
[ 0.41789691  0.61031329 -1.0741859   0.81021236 -0.21717226]

0.19890157127319996
[0.95877295 0.58090603 0.31948023 0.5922294  0.68735366 0.63697436
 0.41185565 0.06698018 0.82370387 0.27509109]

[3 4 6 5]
[910 973 358 291 120 484 402  40 552 174]
