### Search, Sort and Filter in NumPy Arrays

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array([1,2,3,4,2,5,2,5,6,7])

In [3]:
index = np.where(arr ==2)
index

(array([1, 4, 6], dtype=int64),)

In [4]:
np.where(arr%2 == 0)

(array([1, 3, 4, 6, 8], dtype=int64),)

### Searching in Sorted Arrays

In [5]:
data = np.array([x for x in range(9)])
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.searchsorted(data, 5) # Indicates the index position at which the new element would be placed in the sorted array

5

In [7]:
np.searchsorted(data, 5, side = 'right') # Specifies the side from which searching has to be done. Right or Left?

6

In [8]:
np.searchsorted(data, [5,6,10], side = 'left')

array([5, 6, 9], dtype=int64)

### Sorting Arrays

In [9]:
new_arr = np.array([np.random.randint(low = 10, high = 100, size = 10)])
new_arr

array([[77, 45, 95, 87, 77, 50, 48, 13, 87, 57]])

In [10]:
np.sort(new_arr)

array([[13, 45, 48, 50, 57, 77, 77, 87, 87, 95]])

In [11]:
two_dimensional_array = np.array([
    [np.random.randint(low = 10, high = 100, size = 10)], 
    [np.random.randint(low = 10, high = 100, size = 10)]
])
two_dimensional_array

array([[[16, 69, 12, 60, 29, 91, 88, 17, 42, 26]],

       [[45, 12, 82, 65, 96, 67, 60, 38, 41, 40]]])

In [12]:
np.sort(two_dimensional_array)

array([[[12, 16, 17, 26, 29, 42, 60, 69, 88, 91]],

       [[12, 38, 40, 41, 45, 60, 65, 67, 82, 96]]])

### Arithmetic Functions in NumPy

In [13]:
arr = np.array(object = [x for x in range(10)])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.shuffle(arr) # Shuffles the data in place
arr

array([2, 7, 0, 9, 5, 8, 4, 1, 6, 3])

In [15]:
np.random.shuffle(two_dimensional_array)
two_dimensional_array

array([[[16, 69, 12, 60, 29, 91, 88, 17, 42, 26]],

       [[45, 12, 82, 65, 96, 67, 60, 38, 41, 40]]])

In [16]:
data = np.array([1,2,3,4,2,5,2,6,7])
data

array([1, 2, 3, 4, 2, 5, 2, 6, 7])

In [17]:
np.unique(data)

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
np.unique(data, return_index = True)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 8], dtype=int64))

In [19]:
np.unique(data, return_index = True, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 5, 7, 8], dtype=int64),
 array([1, 3, 1, 1, 1, 1, 1], dtype=int64))

In [20]:
new_array = np.array([1,2,3,4,5,6])
np.resize(new_array, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.resize(new_array, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.resize(new_array, (6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Insert and Delete in NumPy

In [23]:
import pandas as pd
import numpy as np

In [24]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [25]:
print(type(data))
print(data.dtype)

<class 'numpy.ndarray'>
int32


In [26]:
np.insert(arr = data, obj = 1, values = 10)

array([ 1, 10,  2,  3,  4])

In [27]:
np.insert(arr = data, obj = 1, values = [10,20,30,40])

array([ 1, 10, 20, 30, 40,  2,  3,  4])

In [28]:
np.insert(arr = data, obj = [1,4], values = -1)

array([ 1, -1,  2,  3,  4, -1])

In [29]:
np.insert(arr = data, obj = [1,4], values = [-1,5])

array([ 1, -1,  2,  3,  4,  5])

In [30]:
two_dimensional_array = np.array([
    [1,2,3], 
    [1,2,3]
])

In [31]:
two_dimensional_array

array([[1, 2, 3],
       [1, 2, 3]])

In [32]:
np.insert(two_dimensional_array, obj = 1, values = 6, axis = 0)

array([[1, 2, 3],
       [6, 6, 6],
       [1, 2, 3]])

In [33]:
np.insert(two_dimensional_array, obj = 1, values = 6, axis = 1)

array([[1, 6, 2, 3],
       [1, 6, 2, 3]])