### Shaping and Re-Shaping Arrays

In [1]:
import pandas as pd
import numpy as np

In [6]:
data = np.array(object = [[1,2,3,4], [1,2,3,4]])
data

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
print(data.shape)

(2, 4)


In [11]:
new_data = np.array([1,2,3,4], ndmin = 4)
new_data.ndim

4

In [12]:
new_data.shape

(1, 1, 1, 4)

In [14]:
"""The outermost array has just one row. The next array also has just one row. The last but one 
array also has just one row. Finally, the last array has 4 columns. Hence, the previous output."""
new_data

array([[[[1, 2, 3, 4]]]])

In [15]:
"""Reshaping Arrays"""
arr = np.array(object = [1,2,3,4,5,6])

In [21]:
reshaped_arr = arr.reshape(3, 2)
# Arguments to the reshape method are, number of rows followed by number of elements in each row
print(reshaped_arr)
print(reshaped_arr.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [29]:
numbers = np.array(object = [x for x in range(9)])
print(numbers, numbers.shape, "\n")

reshaped_numbers = numbers.reshape((3,3))
print(reshaped_numbers, reshaped_numbers.shape)

[0 1 2 3 4 5 6 7 8] (9,) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [32]:
numbers = np.array(object = [x for x in range(12)])
print(numbers, numbers.shape)

"""Here, we're reshaping the 1D array into a 3D array with dimensions (2, 3, 2). The reshape function allows us to rearrange 
the data into a new shape without changing the original data itself.

The original array had 12 elements.
The new shape (2, 3, 2) means:
2 blocks (the first dimension).
Each block has 3 rows (the second dimension).
Each row has 2 elements (the third dimension)."""

reshaped_numbers = numbers.reshape(2,3,2)
print(reshaped_numbers, reshaped_numbers.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] (2, 3, 2)


In [40]:
numbers.reshape(4,3,1)
numbers.reshape(6,2,1)
numbers.reshape(12,1,1)

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]]])

In [43]:
reshaped_numbers.reshape(-1) # -1 is used to reshape the multi-dimensional array to 1-dimensional array
reshaped_numbers.reshape(-1).ndim
reshaped_numbers.reshape(-1).shape

(12,)